language: node_js
sudo: false
branches:
  only:
  - gh-pages
env:
  global:
  - URL="http://github.com/w3c/clipboard-apis/W3CTRMANIFEST"
  - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
  - secure: "VN/dLt9WsmTxswfh1yTbttRsHHAZ3tlxoixu3OPO/arLhpbYDyqHHVF3If8LogWSK/B6hG8CBgGTm4ixtvP5sZ2AaNeyCT3VvcxM2DUXAQMBFsIXVkihuYPZBhC9SPvRGHsYyAm5Bso8QINje7sGXEXMMlaLQIkmSnpZ9wYVSPY="
script:
- echo "ok"
after_success:
- curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION"
  --data "token=$TOKEN"